name: pikpak_auto_invite
on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!.gitignore'
      - '!README.md'
  schedule:
    # 每天午夜执行
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Time
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: Random Wait
        run: |
          # 生成一个随机秒数，范围在0到20000之间（一天的秒数）
          SECONDS_TO_WAIT=$((RANDOM % 10))
          echo "Waiting for $SECONDS_TO_WAIT seconds..."
          sleep $SECONDS_TO_WAIT
      - name: Run
        env:
          INVITE_CODE: ${{secrets.INVITE_CODE}}
        run: python run.py
